---
- hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Installs required system packages listed in the vars.yml file
      apt: pkg={{ item }} state=installed update_cache=true
      with_items: "{{ system_packages }}"
